name: ci

on: 
  pull_request: # only run on pull requests

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    permissions: write-all
    
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Gas snapshot
        id: snapshot
        run: |
          forge snapshot --diff --gas-report > gas.txt
          sed -n '/|/,/Overall gas change:/p' gas.txt > gas_filtered.txt
          
          
      - name: Test coverage
        id: coverage
        run: |
          forge coverage > coverage.txt
          sed -n '/|/,/Total/p' coverage.txt > coverage_filtered.txt
      
      - name: Prepare comment
        id: comment
        run: |
          touch comment.md
          echo "## ðŸ“ˆ Test Coverage Report" >> comment.md
          cat coverage_filtered.txt >> comment.md
          echo "## ðŸ Slither Report" >> comment.md
          echo "check the actions output for slither report" >> comment.md
          echo "## ðŸ“Š Gas Report" >> comment.md
          cat gas_filtered.txt >> comment.md

      - name: Publish Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: comment.md

  
      
      - name: run slither
        continue-on-error: true
        id: slither
        run: |
          pip3 install slither-analyzer
          slither ./src
